name: (Not Ready) Challenge 07 - Build and Push Docker Image to Container Registry

on:
  workflow_dispatch:

env:
  registryName: "Microsoft.ContainerRegistry/registries@2020-11-01-preview.azurecr.io"
  repositoryName: "wth/dotnetcoreapp"
  dockerFolderPath: "./Application/src/RazorPagesTestSample"
  tag: ${{ github.run_number }}

jobs:
  job1:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Test repository variable recall'
        run: echo ${{ vars.AZURE_RESOURCE_GROUP }}

      - name: 'Deploy Azure Bicep'
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          template: ./InfrastructureAsCode/main.bicep

  job2:
      build_and_push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Docker login
          run: docker login ${{ secrets.ACR_REGISTRY_NAME }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

        - name: Docker build
          run: docker build -t ${{ secrets.ACR_REGISTRY_NAME }}/${{ secrets.ACR_REPOSITORY_NAME }}:${{ github.sha }} --build-arg build_version=${{ github.sha }} ${{ secrets.DOCKER_FOLDER_PATH }}

        - name: Docker push
          run: docker push ${{ secrets.ACR_REGISTRY_NAME }}/${{ secrets.ACR_REPOSITORY_NAME }}:${{ github.sha }}