name: First Workflow

on:
  push:
    branches:
      - dan_test

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "step1"

      - name: Step 2
        run: echo "step2"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Use Cowsays action
        uses: actions/checkout@v2

      - name: Run Cowsays
        uses: peter-evans/cowsay-action@v1
        with:
          text: "Hello from Cowsays!"
