name: First Workflow

on:
  push:
    branches:
      - dan_test

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "step1"

      - name: Step 2
        run: echo "step2"
